# -*- coding: utf-8 -*-
{
    'name': "Techfuge Exhibitor Customisations",
    'summary': """ Techfuge Exhibitor Customisations for Event Management""",
    'description': """
        Techfuge Exhibitor Customisations for Event Management
    """,
    'author': "Pragmatic",
    'website': "https://www.pragtech.co.in/",
    'category': 'Events',
    'version': '8.51',
    # any module necessary for this one to work correctly
    'depends': ['techfuge_customisation', 'crm_iap_enrich', 'crm_sms','embeded_url_login','l10n_ae'],
    # always loaded
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/generate_payment_stage_wizard_view.xml',
        'reports/sale_order_report.xml',
        'reports/invoice_report.xml',
        'reports/exhibitor_agreement_report.xml',
        'reports/invitation_letter_report.xml',
        'reports/exhibitor_badge_report.xml',
        'reports/contractor_badge_report.xml',
        'reports/payment_receipt_report.xml',
        'data/ir_sequence_data.xml',
        'data/exhibitor_data.xml',
        'data/ir_action_data.xml',
        'data/mail_data.xml',
        'data/mail_template_data.xml',
        'data/account_report_data.xml',
        # 'views/exhibitor_request_type_views.xml',
        'views/exhibitor_document_type_views.xml',
        'views/exhibitor_contract_views.xml',
        'views/exhibitor_hotel_request_views.xml',
        'views/invitation_letter_requests_views.xml',
        'views/shipment_details_views.xml',
        'views/uploaded_documents_views.xml',
        'views/crm_lead_views.xml',
        'views/event_views.xml',
        'views/event_registration_views.xml',
        'views/res_users_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_views.xml',
        'views/sale_views.xml',
        'views/account_move_views.xml',
        'views/exhibitor_space_type_views.xml',
        'views/contract_purpose_views.xml',
        'views/special_inclusion_info_views.xml',
        'views/exhibitor_contractor_details_views.xml',
        'views/sale_portal_templates.xml',
        'views/portal_layout_inherit_template.xml',
        'views/exhibitor_dashboard_templates.xml',
        'views/exhibitor_dashboard_company_templates.xml',
        'views/exhibitor_dashboard_attendee_templates.xml',
        'views/exhibitor_dashboard_invitation_letter_templates.xml',
        'views/exhibitor_dashboard_hotel_templates.xml',
        'views/exhibitor_dashboard_contractor_templates.xml',
        'views/exhibitor_dashboard_document_templates.xml',
        'views/exhibitor_dashboard_shipment_templates.xml',
        'views/exhibitor_dashboard_other_request_templates.xml',
        'views/exhibitor_dashboard_scan_badge_templates.xml',
        'views/exhibitor_agreement_portal_template.xml',
        'data/decimal_precision.xml',
        'views/exhibitor_dashboard_other_request_invoice.xml',
        'views/exhibitor_dashboard_templates.xml',
        'views/portal_payment_reciept_details.xml',
        'views/product_template.xml',
        'views/event_activity_location.xml',
        'data/duplicate_email_for_lead.xml',
        'views/mail_compose_message.xml',
        'views/onsite_badge_printing/exhibitor_badge_printing_qr_code.xml',
        'reports/qrcode_for_exhibitor_registration.xml',
        'views/exhibitor_stand_details.xml',
        'views/onsite_badge_printing/visit_badge_printing_qr_code.xml',
        'reports/qrcode_for_visitors_registration.xml',
        'views/report_bank_details/report_bank_details.xml'
    ],
    'assets': {
        'web.assets_frontend': [
            'techfuge_exhibitor_customisation/static/src/css/exhibitor_dashboard.css',
            'techfuge_exhibitor_customisation/static/src/js/exhibitor_dashboard.js',
        ],
        'web.report_assets_common': [
            'techfuge_exhibitor_customisation/static/src/css/proforma_invoice.css',
            'techfuge_exhibitor_customisation/static/src/scss/exhibitor_badge_report.scss',
        ],
    },
    'license': 'LGPL-3',
}
