# -*- coding: utf-8 -*-

from . import res_users
from . import product_template
from . import crm
from . import res_partner
from . import res_company
from . import special_inclusion_info
from . import exhibitor_space_type
from . import contract_purpose
from . import sale
from . import event
from . import event_registration
from . import account_move
from . import exhibitor_request_type
from . import exhibitor_document_type
from . import exhibitor_contract
from . import exhibitor_commercial_items
from . import exhibitor_stand_details
from . import exhibitor_invitation_letter_request
from . import exhibitor_hotel_request
from . import exhibitor_uploaded_documents
from . import exhibitor_other_request
from . import exhibitor_contractor_details
from . import contractor_uploaded_documents
from . import exhibitor_package_components
from . import exhibitor_payment_stages
from . import exhibitor_shipment_details
from . import shipment_uploaded_documents
from . import so_stand_details
from . import contract_stand_details
from . import account_partner_ledger
from . import mail_compose_message
